version: "3"
services:
  app1:
    build: 
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/data"
    networks:
      - uaifi

  app2:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_URL=https://github.com/dg-delbank/docker-compose-newtry-addon.git
    ports:
      - "3001:3000"  
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/data"
    networks:
      - uaifi

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - uaifi

networks:
  uaifi: